name: Build and Push Docker Image

on:
  # This workflow is now triggered manually OR by the API call from the sync workflow
  workflow_dispatch:
  # We keep the push trigger in case you push manual commits to master
#  push:
#    branches:
3      - master

env:
  DOCKER_REPO_NAME: nuviostreams
  DOCKER_TAG: latest

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set DOCKER_IMAGE_FULL_NAME
        id: set_image_name
        run: |
          echo "DOCKER_IMAGE_FULL_NAME=${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO_NAME }}" >> "$GITHUB_ENV"

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_FULL_NAME }}:${{ env.DOCKER_TAG }}
          file: ./Dockerfile

      - name: Verify image push
        run: echo "Docker image ${{ env.DOCKER_IMAGE_FULL_NAME }}:${{ env.DOCKER_TAG }} pushed successfully!"
