name: Build and Push Docker Image

on:
  push:
    branches:
      - master # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual triggering of the workflow

env:
  # DOCKER_IMAGE_NAME will be constructed in the job using the DOCKER_USERNAME secret
  DOCKER_REPO_NAME: nuviostreams # Only the repository part of the image name
  DOCKER_TAG: latest

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: Production # Optional: You can define an environment for deployment if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set DOCKER_IMAGE_FULL_NAME
        id: set_image_name
        run: |
          echo "DOCKER_IMAGE_FULL_NAME=${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO_NAME }}" >> "$GITHUB_ENV"
        # This step creates a new environment variable DOCKER_IMAGE_FULL_NAME
        # that combines the Docker Hub username secret and the DOCKER_REPO_NAME.

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_FULL_NAME }}:${{ env.DOCKER_TAG }}
          file: ./Dockerfile # Explicitly specify the Dockerfile path

      - name: Verify image push
        run: echo "Docker image ${{ env.DOCKER_IMAGE_FULL_NAME }}:${{ env.DOCKER_TAG }} pushed successfully!"
