name: Sync Fork with Upstream

on:
  schedule:
    # Run every day at 8 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # A PAT is still recommended for this method
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Get commit hash before sync
        id: pre_sync
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/tapframe/NuvioStreamsAddon.git

      - name: Fetch upstream branches
        run: git fetch upstream

      - name: Merge upstream and resolve conflicts
        run: |
          # The .gitattributes file will protect your Dockerfile and .yaml files.
          # The -X theirs option will auto-resolve all other conflicts using the upstream version.
          git merge --no-edit -X theirs upstream/master || true

      - name: Push changes to fork
        run: git push origin master

      - name: Get commit hash after sync
        id: post_sync
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      # --- THIS IS THE CORRECTED STEP ---
      - name: Trigger Docker Build on Change
        if: steps.pre_sync.outputs.sha != steps.post_sync.outputs.sha
        env:
          # The GITHUB_TOKEN is a special secret that is automatically created and provided.
          # For cross-workflow triggers, your PAT is more reliable.
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Changes detected. Triggering the Docker build workflow..."
          gh workflow run "DockerBuild" --ref ${{ github.ref_name }}

      - name: Report no changes
        if: steps.pre_sync.outputs.sha == steps.post_sync.outputs.sha
        run: echo "Repository is already up-to-date. No new changes from upstream. Docker build skipped."
