name: Sync Fork with Upstream

on:
  schedule:
    # Run every day at 8 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We need a PAT here to push and to trigger the next workflow
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Get commit hash before sync
        id: pre_sync
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/tapframe/NuvioStreamsAddon.git

      - name: Fetch upstream branches
        run: git fetch upstream

      - name: Merge upstream and resolve conflicts
        run: |
          # The .gitattributes file will protect your Dockerfile and .yaml files.
          # The -X theirs option will auto-resolve all other conflicts using the upstream version.
          git merge --no-edit -X theirs upstream/master || true

      - name: Push changes to fork
        run: git push origin master

      - name: Get commit hash after sync
        id: post_sync
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Check for changes and trigger Docker build
        # This step only runs if the commit hash has changed
        if: steps.pre_sync.outputs.sha != steps.post_sync.outputs.sha
        uses: benc-uk/workflow-dispatch-action@v1
        with:
          workflow: Build and Push Docker Image  # Name of the workflow file to trigger
          token: ${{ secrets.PAT }}

      - name: Report no changes
        if: steps.pre_sync.outputs.sha == steps.post_sync.outputs.sha
        run: echo "Repository is already up-to-date. No new changes from upstream. Docker build skipped."
